# Generated by Django 2.2.7 on 2020-03-05 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_auto_20200224_1953'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sabscriber',
            options={'verbose_name': 'MySabscriber', 'verbose_name_plural': 'A lot of Sabscribers'},
        ),
    ]
