# Generated by Django 2.2.7 on 2020-03-05 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200305_0921'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinorder',
            options={'verbose_name': 'Product in Order', 'verbose_name_plural': 'Products in Order'},
        ),
    ]
